// Generated by dojo-bindgen on Sat, 22 Feb 2025 20:14:49 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::Player` model
public class evolute_duel_Player : ModelInstance {
    [ModelField("player_id")]
        public FieldElement player_id;

        [ModelField("username")]
        public FieldElement username;

        [ModelField("balance")]
        public ushort balance;

        [ModelField("games_played")]
        public FieldElement games_played;

        [ModelField("active_skin")]
        public byte active_skin;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        