// Generated by dojo-bindgen on Sat, 22 Feb 2025 11:41:10 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `evolute_duel::packing::GameStatus` enum

// Model definition for `evolute_duel::models::GameCreated` model
public class evolute_duel_GameCreated : ModelInstance {
    [ModelField("host_player")]
        public FieldElement host_player;

        [ModelField("status")]
        public GameStatus status;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        