// Generated by dojo-bindgen on Tue, 18 Feb 2025 15:33:04 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `evolute_duel::models::GameStatus` enum
public abstract record GameStatus() : Enum {
    public record Finished() : GameStatus;
    public record Created() : GameStatus;
    public record Canceled() : GameStatus;
    public record InProgress() : GameStatus;
}

// Type definition for `core::option::Option::<core::felt252>` enum



// Model definition for `evolute_duel::models::Game` model
public class evolute_duel_Game : ModelInstance {
    [ModelField("host_player")]
        public FieldElement host_player;

        [ModelField("status")]
        public GameStatus status;

        [ModelField("board_id")]
        public Option<FieldElement> board_id;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        