// Generated by dojo-bindgen on Mon, 24 Feb 2025 09:31:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::eventsModels::ESnapshotCreateFailed` model
public class evolute_duel_SnapshotCreateFailed : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("board_id")]
        public FieldElement board_id;

        [ModelField("board_game_state")]
        public GameState board_game_state;

        [ModelField("move_number")]
        public byte move_number;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        