// Generated by dojo-bindgen on Mon, 24 Feb 2025 09:31:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Model definition for `evolute_duel::eventsModels::ESkiped` model
public class evolute_duel_Skiped : ModelInstance {
    [ModelField("move_id")]
        public FieldElement move_id;

        [ModelField("player")]
        public FieldElement player;

        [ModelField("prev_move_id")]
        public Option<FieldElement> prev_move_id;

        [ModelField("board_id")]
        public FieldElement board_id;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        