// Generated by dojo-bindgen on Tue, 18 Feb 2025 15:33:04 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::Rules` model
public class evolute_duel_Rules : ModelInstance {
    [ModelField("id")]
        public FieldElement id;

        [ModelField("deck")]
        public byte[] deck;

        [ModelField("edges")]
        public (byte, byte) edges;

        [ModelField("joker_number")]
        public byte joker_number;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        