// Generated by dojo-bindgen on Mon, 24 Feb 2025 09:31:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Model definition for `evolute_duel::eventsModels::EGameCanceled` model
public class evolute_duel_GameCanceled : ModelInstance {
    [ModelField("host_player")]
        public FieldElement host_player;

        [ModelField("status")]
        public GameStatus status;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        