// Generated by dojo-bindgen on Mon, 24 Feb 2025 09:31:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::eventsModels::ERulesCreated` model
public class evolute_duel_RulesCreated : ModelInstance {
    [ModelField("rules_id")]
        public FieldElement rules_id;

        [ModelField("edges")]
        public (byte, byte) edges;

        [ModelField("joker_number")]
        public byte joker_number;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        