// Generated by dojo-bindgen on Wed, 19 Feb 2025 11:08:01 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `core::option::Option::<core::felt252>` enum


// Model definition for `evolute_duel::models::Move` model
public class evolute_duel_Move : ModelInstance {
    [ModelField("id")]
        public FieldElement id;

        [ModelField("player_side")]
        public PlayerSide player_side;

        [ModelField("prev_move_id")]
        public Option<FieldElement> prev_move_id;

        [ModelField("tile")]
        public Option<byte> tile;

        [ModelField("rotation")]
        public byte rotation;

        [ModelField("is_joker")]
        public bool is_joker;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        