// Generated by dojo-bindgen on Sat, 22 Feb 2025 17:51:40 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::PotentialRoadContests` model
public class evolute_duel_PotentialRoadContests : ModelInstance {
    [ModelField("board_id")]
        public FieldElement board_id;

        [ModelField("roots")]
        public byte[] roots;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        