// Generated by dojo-bindgen on Sun, 23 Feb 2025 13:49:03 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Type definition for `evolute_duel::packing::GameStatus` enum
public abstract record GameStatus() : Enum {
    public record Finished() : GameStatus;
    public record Created() : GameStatus;
    public record Canceled() : GameStatus;
    public record InProgress() : GameStatus;
}


// Model definition for `evolute_duel::models::Game` model
public class evolute_duel_Game : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("status")]
        public GameStatus status;

        [ModelField("board_id")]
        public Option<FieldElement> board_id;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        