// Generated by dojo-bindgen on Mon, 24 Feb 2025 09:31:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Model definition for `evolute_duel::eventsModels::EGameJoinFailed` model
public class evolute_duel_GameJoinFailed : ModelInstance {
    [ModelField("host_player")]
        public FieldElement host_player;

        [ModelField("guest_player")]
        public FieldElement guest_player;

        [ModelField("host_game_status")]
        public GameStatus host_game_status;

        [ModelField("guest_game_status")]
        public GameStatus guest_game_status;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        