// Generated by dojo-bindgen on Sat, 22 Feb 2025 20:14:49 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `evolute_duel::packing::GameState` enum
public abstract record GameState() : Enum {
    public record InProgress() : GameState;
    public record Finished() : GameState;
}

// Model definition for `evolute_duel::models::Board` model
public class evolute_duel_Board : ModelInstance {
    [ModelField("id")]
        public FieldElement id;

        [ModelField("initial_edge_state")]
        public byte[] initial_edge_state;

        [ModelField("available_tiles_in_deck")]
        public byte[] available_tiles_in_deck;

        [ModelField("top_tile")]
        public Option<byte> top_tile;

        [ModelField("state")]
        public (byte, byte, byte)[] state;

        [ModelField("player1")]
        public (FieldElement, PlayerSide, byte) player1;

        [ModelField("player2")]
        public (FieldElement, PlayerSide, byte) player2;

        [ModelField("blue_score")]
        public ushort blue_score;

        [ModelField("red_score")]
        public ushort red_score;

        [ModelField("last_move_id")]
        public Option<FieldElement> last_move_id;

        [ModelField("game_state")]
        public GameState game_state;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        