// Generated by dojo-bindgen on Sat, 22 Feb 2025 20:14:49 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::Snapshot` model
public class evolute_duel_Snapshot : ModelInstance {
    [ModelField("snapshot_id")]
        public FieldElement snapshot_id;

        [ModelField("player")]
        public FieldElement player;

        [ModelField("board_id")]
        public FieldElement board_id;

        [ModelField("move_delta")]
        public byte move_delta;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        